service: todolist-api-sls
frameworkVersion: "3"

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminDeleteUser
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - !GetAtt TodoListUserPool.Arn
            - !GetAtt TodosTable.Arn
  environment:
    COGNITO_CLIENT_ID: !Ref TodoListUserPoolClient
    COGNITO_POOL_ID: !Ref TodoListUserPool
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt TodoListUserPool.ProviderURL
        audience:
          - !Ref TodoListUserPoolClient

custom:
  Esbuild:
  bundle: true
  minify: true
  sourcemap: false
  target: node20
  exclude:
    - "@aws-sdk/*"
  platform: node
  concurrency: 10

resources:
  Resources:
    TodoListUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: TodoListUserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
    TodoListUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: TodoListUserPoolClient
        UserPoolId: !Ref TodoListUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AccessTokenValidity: 1
        RefreshTokenValidity: 30
        TokenValidityUnits:
          AccessToken: days
          RefreshToken: days
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodosTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S #S == String / N == Number / B == Binary
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          method: GET
          path: /hello
  cognitoCustomMessage:
    handler: src/functions/auth/cognitoCustomMessage.handler
    events:
      - cognitoUserPool:
          pool: TodoListUserPool
          trigger: CustomMessage
          existing: true
          forceDeploy: true
  signUp:
    handler: src/functions/auth/signUp.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-up
  signIn:
    handler: src/functions/auth/signIn.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-in
  accountConfirmation:
    handler: src/functions/auth/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/verify-account
  refreshToken:
    handler: src/functions/auth/refreshToken.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh-token
  forgotPassword:
    handler: src/functions/auth/forgotPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/forgot-password
  resetPassword:
    handler: src/functions/auth/resetPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/reset-password
  deleteAccount:
    handler: src/functions/accounts/deleteAccount.handler
    events:
      - httpApi:
          method: DELETE
          path: /accounts/{accountId}
  createTodo:
    handler: src/functions/todos/createTodo.handler
    events:
     - httpApi:
          method: POST
          path: /todos
          authorizer:
            name: CognitoAuthorizer
  getTodos:
    handler: src/functions/todos/getTodos.handler
    events:
     - httpApi:
          method: GET
          path: /todos
          authorizer:
            name: CognitoAuthorizer
